on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - run: git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run build:css
      - run: npm run lint
      - run: npm test
      - uses: codecov/codecov-action@v3
