on: [push, pull_request]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - run: git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npx c8 npm test
      - run: npx c8 report --reporter=text-lcov > coverage.lcov
      - uses: codecov/codecov-action@v2
